# Generated by Django 2.0 on 2018-06-30 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0002_auto_20180626_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='have_taxes',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='edited',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='invoice',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='incomes.InvoiceCategory'),
        ),
    ]
