# Generated by Django 2.0 on 2018-06-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0003_auto_20180630_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='edited',
        ),
    ]
