# Generated by Django 2.0 on 2018-06-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='timestamp',
            field=models.DateField(blank=True),
        ),
    ]
