# Generated by Django 2.0 on 2018-06-30 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0004_remove_expense_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date_created']},
        ),
    ]
