# Generated by Django 2.0.5 on 2018-07-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0006_auto_20180708_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
