# Generated by Django 2.0 on 2018-06-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_auto_20180626_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='crops',
            field=models.ManyToManyField(blank=True, to='farms.Crop'),
        ),
    ]
