# Generated by Django 2.0.5 on 2018-06-13 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_auto_20180613_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='crops',
        ),
    ]
