# Generated by Django 2.0.5 on 2018-06-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_remove_farm_crops'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='date_test',
            field=models.DateField(null=True),
        ),
    ]
