# Generated by Django 2.0 on 2018-06-27 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_auto_20180626_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='crops',
        ),
        migrations.AddField(
            model_name='crop',
            name='farm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crops', to='farms.Farm'),
        ),
        migrations.AddField(
            model_name='crop',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
