# Generated by Django 2.0.5 on 2018-06-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0005_farm_date_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
