# Generated by Django 2.0.5 on 2018-07-05 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0005_auto_20180627_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tree',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trees', to=settings.AUTH_USER_MODEL),
        ),
    ]
