# Generated by Django 2.0 on 2018-06-14 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0006_farm_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='crops',
            field=models.ManyToManyField(blank=True, limit_choices_to={'fieldfarm__user': models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)}, null=True, to='farms.Crop'),
        ),
    ]
