# Generated by Django 2.0.5 on 2018-07-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0007_auto_20180721_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
